version: 1
update_configs:
  - package_manager: "submodules"
    directory: "./"
    update_schedule: "daily"
    allowed_updates:
      - match:
          dependency_name: "7-test"
    ignored_updates:
      - match:
          dependency_name: "7-sorter-utility"
